CREATE TABLE IF NOT EXISTS projects (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL DEFAULT "",
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS tasks (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	project_id INT UNSIGNED NOT NULL DEFAULT 0,
	name VARCHAR(40) NOT NULL DEFAULT "",
	due_at DATETIME NOT NULL DEFAULT 0,
	completed BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
);
